CrazyLib/config/routes.rb
CrazyLib::Application.routes.draw do
  resources :book_categories
  
  
  match "admin/book_topic"=> "book_categories#index"
  match "admin/show_transactions" => 'admin#show_transactions'
  match "admin/send_email" => 'admin#send_email'
  match "admin" => 'admin#index'
  match "admin/add_book"=> "books#new"
  match "admin/show_users"=> "admin#show_users"
  match "admin/show_books" => "admin#show_books"
  match "admin/show_moderates" => "admin#show_moderates"
  match "admin/edit_books" => "books#edit"
  match "admin/return_book" => "transactions#search"
  devise_for :add_column_to_users
  devise_for :users
  match "/users" => "registrations#new"
  get "/users/add_to_moderate"
  get "/users/remove_from_moderate"
  match "users/feed_back" => "users#feed_back"
  resources :users, :only => [:show]

  get "transactions/destroy"
  get "transactions/new"
  get "transactions/userhistory"
  get "transactions/return"
  get "transactions/receive"
  get "books/popular"
  get "books/newbook"
  get "books/view"
  get "books/search"
  match "view"=>"books#view"
  resources :books
  
  
 

  
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'
  match '/faq' => 'pages#faq'
  match 'rule' => 'pages#rule'

  root :to=>"books#index"

end

CrazyLib/app/models/book_category.rb
class BookCategory < ActiveRecord::Base
end

CrazyLib/app/controllers/book_categories_controller.rb
class BookCategoriesController < ApplicationController
  layout 'admin'
  # GET /book_categories
  # GET /book_categories.json
  def index
    @book_categories = BookCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @book_categories }
    end
  end

  # GET /book_categories/1
  # GET /book_categories/1.json
  def show
    @book_category = BookCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book_category}
    end
  end

  # GET /book_categories/new
  # GET /book_categories/new.json
  def new
    @book_category = BookCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book_category }
    end
  end

  # GET /book_categories/1/edit
  def edit
    @book_category = BookCategory.find(params[:id])
  end

  # POST /book_categories
  # POST /book_categories.json
  def create
    @book_category = BookCategory.new(params[:book_category])

    respond_to do |format|
      if @book_category.save
        format.html { redirect_to @book_category, notice: 'Book category was successfully created.' }
        format.json { render json: @book_category, status: :created, location: @book_category }
      else
        format.html { render action: "new" }
        format.json { render json: @book_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /book_categories/1
  # PUT /book_categories/1.json
  def update
    @book_category = BookCategory.find(params[:id])

    respond_to do |format|
      if @book_category.update_attributes(params[:book_category])
        format.html { redirect_to @book_category, notice: 'Book category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_categories/1
  # DELETE /book_categories/1.json
  def destroy
    @book_category = BookCategory.find(params[:id])
    @book_category.destroy

    respond_to do |format|
      format.html { redirect_to book_categories_url }
      format.json { head :no_content }
    end
  end
end

CrazyLib/app/helpers/book_categories_helper.rb
module BookCategoriesHelper
end

CrazyLib/app/views/book_categories/_form.html.haml
= form_for @book_category do |f|
  -if @book_category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book_category.errors.count, "error")} prohibited this book_category from being saved:"
      %ul
        - @book_category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label (t :name)
    = f.text_field :name
  .actions
    = f.submit (t :save),:class=>"btn"

CrazyLib/app/views/book_categories/edit.html.haml
-if user_signed_in?
  -if current_user.group ==3
    %h1= t :editing_book_topic
    
    = render 'form'
    
    = link_to (t :show), @book_category
    \|
    = link_to (t :back), book_categories_path

CrazyLib/app/views/book_categories/index.html.haml
-if user_signed_in?
  -if current_user.group ==3
    %h1= (t :listing_book_topic)
    
    %table(class="table table-bordered")
      %tr
        %th(class="label-success") Name
        %th(class="label-success")
        %th(class="label-success")
        %th(class="label-success")
    
      - @book_categories.each do |book_category|
        %tr
          %td= book_category.name
          %td= link_to (t :show), book_category
          %td= link_to (t :edit), edit_book_category_path(book_category) + "?locale=" + I18n.locale.to_s
          %td= link_to (t :destroy), book_category, :confirm => (t :are_you_sure), :method => :delete
    
    %br
    
    = link_to 'New Book topic', new_book_category_path

CrazyLib/app/views/book_categories/new.html.haml
-if user_signed_in?
  -if current_user.group ==3
    %h1 New book topic
    
    = render 'form'
    
    = link_to 'Back', book_categories_path

CrazyLib/app/views/book_categories/show.html.haml
-if user_signed_in?
  -if current_user.group ==3
    %p#notice= notice
    
    %p
      %b Name:
      = @book_category.name
    
    = link_to 'Edit', edit_book_category_path(@book_category)
    \|
    = link_to 'Back', book_categories_path
     