CrazyLib/config/routes.rb
CrazyLib::Application.routes.draw do
  resources :book_categories
  
  
  match "admin/book_topic"=> "book_categories#index"
  match "admin/show_transactions" => 'admin#show_transactions'
  match "admin/send_email" => 'admin#send_email'
  match "admin" => 'admin#index'
  match "admin/add_book"=> "books#new"
  match "admin/show_users"=> "admin#show_users"
  match "admin/show_books" => "admin#show_books"
  match "admin/show_moderates" => "admin#show_moderates"
  match "admin/edit_books" => "books#edit"
  match "admin/return_book" => "transactions#search"
  devise_for :add_column_to_users
  devise_for :users
  match "/users" => "registrations#new"
  get "/users/add_to_moderate"
  get "/users/remove_from_moderate"
  match "users/feed_back" => "users#feed_back"
  resources :users, :only => [:show]

  get "transactions/destroy"
  get "transactions/new"
  get "transactions/userhistory"
  get "transactions/return"
  get "transactions/receive"
  get "books/popular"
  get "books/newbook"
  get "books/view"
  get "books/search"
  match "view"=>"books#view"
  resources :books
  
  
 

  
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'
  match '/faq' => 'pages#faq'
  match 'rule' => 'pages#rule'

  root :to=>"books#index"

end

CrazyLib/app/models/book.rb
class Book < ActiveRecord::Base
  self.inheritance_column = :user_type
  validates :title, :presence => true
   validates_numericality_of   :total_page, :greater_than =>0
   validates_numericality_of  :quantity, :greater_than=>0
  def self.searchByTitle(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
    #find(:all)
    end
  end
  def bookTopic(topic)
    #case topic
     # when 1
      #  return "Web development"
      #when 2
      #  return "Database"
      #else
      #  return "Others"
    #end
    category = BookCategory.find(:first,:conditions=>{:id=>topic.to_i})
    if (category)
      return category.name
    else 
       return "Other"
    end
  end
     
    
  def self.search(filter,keyword)
    puts "searching"
    if keyword
      case filter
      when 0 #all
        find(:all,:conditions=>['title LIKE ? or author LIKE ? or brief_content LIKE ?',"%#{keyword}%","%#{keyword}%","%#{keyword}%"])
      when 1 #title
        find(:all, :conditions => ['title LIKE ?', "%#{keyword}%"])
      when 2 #author
        find(:all, :conditions => ['author LIKE ?', "%#{keyword}%"])
      when 3 #desciption
        find(:all, :conditions => ['brief_content LIKE ?', "%#{keyword}%"])
      else 
        find(:all)
      end
      
    else
      find(:all)
    end
  end
  
end

CrazyLib/app/controllers/books_controller.rb
class BooksController < ApplicationController
  layout 'admin', :only => [:new,:show_all,:edit]
  # GET /books
  # GET /books.json
  def index
    topics = Book.select(:topic).uniq
    @books = Array.new
    topics.each do |topic|
      @book = Array.new
      @book = Book.find(:all,:conditions=>{:topic=>topic.topic})
      @books.push(@book)
    end
    @sciences = Book.find(:all,:conditions=>{:topic=>"1"});
    respond_to do |format|
      format.html # view.html
      format.json { render json: @sciences }
    end
  end
  
  def view
  book =  Book.find(params[:id]);
  views = book.seen_by.to_i+1; 
  book.update_attributes(:seen_by=>views);
  end
  #
  def newbook
  @books = Book.find(:all,:order=>"created_at DESC",:limit=>20);
  end
  
  def popular
  @books = Book.find(:all,:order=>"seen_by DESC",:limit=>20);
  end
  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    if (!@book.current_quantity)
      @book.update_attributes(:current_quantity=>:quantity)
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
    @book = Book.find(:all,:conditions=>{:bookId=>params[:id]});
    respond_to do|format|
      format.html
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @book }
    end
  end
  
  def page
  respond_to do |format|
      format.html {render :layout => false}
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    params[:book][:current_quantity]=params[:book][:quantity]
    params[:book][:date_of_storing]=Date.today
    @book = Book.new(params[:book])
    respond_to do |format|
      if @book.save
        format.html { redirect_to "/admin/show_books", notice: 'Book was successfully created.' }
        #format.json { render json: @book, status: :created, location: @book }
      else
        format.html { redirect_to "/admin/add_book", notice: 'Failed'}
        #format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])
  #"/books/view?topic=<%=@book.topic%>&id=<%=@book.id%>"
    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to "/admin/show_books", notice: 'Book was successfully updated.' }
       format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  #def searchByTitle
   # @books = Book.searchByTitle params[:search]
  #end

  def search
    if params[:keyword]
      @books = Book.search(params[:filter].to_i ,params[:keyword])
    else
      @book = Book.find(:all)
    end
  end
  def show_all
    @books=Book.all
  end
end

CrazyLib/app/helpers/books_helper.rb
module BooksHelper
end

CrazyLib/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

	<ul>
		<% @book.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<table class="table table-">
	<tr>
		<td>
		<div class="field">
			<%= f.label :title %>
			<%= f.text_field :title ,:class=>"span4 pull-left"%>
		</div>
		<div class="field">
			<%= f.label :author %>
			<%= f.text_field :author ,:class=>"span4"%>
		</div>
		<div class="field">
			<%= f.label :publisher %>
			<%= f.text_field :publisher ,:class=>"span4"%>
		</div></td>
		<td>
		<div class="field">
			<%= f.label :total_page %>
			<%= f.number_field :total_page ,:class=>"span3", :min=>1%>
		</div>
		<div class="field">
			<%= f.label :topic %>
			<%= f.collection_select :topic, BookCategory.find(:all), :id, :name%>
		</div>
		<div class="field">
			<%= f.label :quantity %>
			<%= f.number_field :quantity ,:class=>"span3", :min=>1%>
		</div></td>
		<td>
		<div class="field">
			<%= f.label :brief_content %>
			<%= f.text_area :brief_content,:class=>"span6",:rows=>9 %>
		</div></td>
	</tr>
	<tr>
		<td></td>
		<td>
		<div class="actions">
			<center>
				<%= f.submit :class=>"btn "%>
			</center>
		</div></td>
		<td></td>
	</tr>
</table>

<% end %>

CrazyLib/app/views/books/_onebook.html.erb
<link href="http://fonts.googleapis.com/css?family=Berkshire Swash&subset=latin" rel="stylesheet" type="text/css">
<div class="slideshow">
	<% @slides = Book.find(:all,:conditions=>{:topic=>params[:topic]});%>
	<% @book =  Book.find(:all,:conditions=>{:id=>params[:id]});%>
	<div class="slidesContainer">
		<div>
			<% i=0;%>
			<%@slides.each do |slide|%>
			<%if(i%6==0)%>
			<div class="slide" >
				<%end%>
				<li class="span2">
					<a href="view?topic=<%= slide.topic%>&id=<%= slide.id%>&locale=<%=I18n.locale%>" class="thumbnail" style="margin-bottom:5px;"> <img src="../assets/<%= slide.image_url%>" alt=""></img> </a>
				</li>
				<%if(i%6==5)%>
			</div>
			<%end%>
			<% i=i+1%>
			<%end%>
		</div>
	</div>
</div>
</div>
<div class="books-one-details">
	<div class="row-fluid" style="font-family:Berkshire Swash;">
		<li class="span3">
			<a class="thumbnail"> <img src="../assets/<%= @book[0].image_url%>" alt=""></img> </a>
		</li>
		<li class="span6" >
			<span style="font-size:20px" class="label label-success"><%= @book[0].title%></span>
			<hr>
			<table class="table table-bordered" >
				<tr>
					<td><span class="label "><%=t :book_id%></span></td>
					<td><span class="label label-important" style="cursor:pointer"><%= @book[0].id%></span></td>
				</tr>
				<tr>
					<td><span class="label "><%=t :book_author%></span></td>
					<td><span class="label label-info"style="cursor:pointer"><%= @book[0].author%></span></td>
				</tr>
				<tr>
					<td><span class="label "><%=t :book_publisher%></span></td>
					<td><span class="label label-info" style="cursor:pointer"><%= @book[0].publisher%></span></td>
				</tr>
				<tr>
					<td><span class="label "><%=t :book_category%></span></td>
					<td><span class="label label-info" style="cursor:pointer"><%= @book[0].id%></span></td>
				</tr>
				<tr>
					<td><span class="label "><%=t :book_rating%></span></td>
					<td><span class="label label-info" style="cursor:pointer">5.0(static)</span></td>
				</tr>
			</table>
		</li>
		<li class="span3">
			<br/>
			<hr>
			<table class="table table-bordered">
				<tr>
					<td><span class="label label-inverse"><%=t :book_quantity%></span></td>
					<td><span class="badge badge-warning" style="cursor:pointer"><%= @book[0].quantity%></span></td>
				</tr>
				<tr>
					<td><span class="label label-inverse"><%=t :book_require%></span></td>
					<td><span class="badge badge-warning" style="cursor:pointer"><%= @book[0].quantity-@book[0].current_quantity%></span></td>
				</tr>
				<tr>
					<div class="hide">
						<span class="label label-inverse"><%=t :book_nosatisfied%></span><span class="badge badge-warning" style="margin-left:10px;cursor:pointer">7(static)</span></br>
						<span class="label label-inverse"><%=t :book_position%></span><span class="badge badge-warning" style="margin-left:10px;cursor:pointer">8(static)</span></br>
						<span class="label label-inverse"><%=t :book_notation%></span><span class="badge badge-warning" style="margin-left:10px;cursor:pointer">9(static)</span></br>
					</div>

				</tr>
				</br>
			</table>
			<br/>
			<% if (user_signed_in?)%>
			<% if !current_user.is_borrowed(@book[0].id )%>
			<a href="/transactions/new?id=<%= @book[0].id%>">
			<button class="btn btn-mini" type="button">
				<span class="icon-refresh"> </span> <%=t :book_order%>
			</button> </a>
			<% else %>
			<a href="/transactions/destroy?bookid=<%= @book[0].id%>">
			<button class="btn btn-mini" type="button">
				<span class="icon-refresh"> </span> <%=t :book_cancel_oder%>
			</button> </a>
			<% end %>
			<button class="btn btn-mini" type="button">
				<span class="icon-eye-open"> </span> <%=t :book_check_later%>
			</button>
			<% end %>
		</li>
	</div>
</div>
<div class="books-one-details">
	<div class="row-fluid">
		<div class="span6">
			<strong><%=t :book_summary%></strong>
			<hr>
			<%= @book[0].brief_content%>
		</div>
		<div class="span6">
			<strong><%=t :book_comment%></strong>
			<hr>
			<div >
				<img src="http://placehold.it/50x50" class="pull-left img-rounded"></img>
				<div class="alert alert-success " style="margin-left:67px;">
					<strong style="color:#F89406;">user1 </strong><span style="color:#999999">says:</span/>
						<br>
						comment 1
						<br>
				</div>
			</div>
			<div >
				<img src="http://placehold.it/50x50" class="pull-right img-rounded"></img>
				<div class="alert alert-success " style="margin-right:67px;">
					<strong style="color:#F89406;">user2 </strong><span style="color:#999999">says:</span/>
						<br>
						comment 2
						<br>
				</div>
			</div>
			<div>
				<textarea class="span12" ></textarea>
				<button class="btn">
					<%=t :book_send%>
				</button>
			</div>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		var slides = $('.slide');
		var slideWidth = 950;
		var numberOfSlides = slides.length;
		var currentPosition = Math.round(Math.random(0) * (numberOfSlides - 1));
		slides.wrapAll('<div id="slideInner"></div>');
		$('#slideInner').css('width', slideWidth * numberOfSlides);
		$('.slideshow').prepend('<span class="control" id="leftControl"></span>').append('<span class="control" id="rightControl"></span>')
		manageControls(currentPosition);
		$('#slideInner').css('margin-left', slideWidth * (-currentPosition));
		$('.control').bind('click', function() {
			currentPosition = ($(this).attr('id') == 'rightControl') ? currentPosition + 1 : currentPosition - 1;

			manageControls(currentPosition);
			$('#slideInner').animate({
				'margin-left' : slideWidth * (-currentPosition)
			})
		});

		function manageControls(position) {
			// Hide left arrow if position is first slide
			if (position == 0) {
				$('#leftControl').hide()
			} else {
				$('#leftControl').show()
			}
			// Hide right arrow if position is last slide
			if (position == numberOfSlides - 1) {
				$('#rightControl').hide()
			} else {
				$('#rightControl').show()
			}
		}

	}); 
</script>

CrazyLib/app/views/books/_search.html.erb
<div class="offset6">
	<div class="form-search">
		<%= form_tag books_search_path + "?locale=" + I18n.locale.to_s, method: :get do %>
		<div class="input-append controls controls-row">
			<%= select_tag "filter","<option value='0'>All</option><option value='1' >Tittle</option><option value='2'>Author</option><option value='3'>Description</option>".html_safe,:style=>"width:25%" %>
			<%= text_field_tag :keyword, params[:keyword] %>
			<%= text_field_tag :locale,params[:locale],:value=>I18n.locale,:class=>"hide"%>
			<button "Search" class="btn"><%=t :search%></button>
		</div>
	</div>
	<i class="hide" id="filter-selected"><%= params[:filter]%></i>
	<i class="hide" id="keyword-find"><%=params[:keyword]%></i>
	<% end %>
	
</div>
<%= render 'search_results'%>
<script>
	$(document).ready(function(){
		var index = $('#filter-selected').text()
		$('#filter option:eq('+index+')').attr("selected","selected");
		if(parseInt(index)==0){
			var len = $('table tbody td').length;
			for(var i=0;i<len;i++){
				var keyword = $('#keyword-find').text();
				var elem = $('table tbody td:eq('+i+')');
				var name = elem.text();
				var upper = name.toLocaleUpperCase();
				var length = name.length;
				if(upper.indexOf(keyword.toLocaleUpperCase())!=-1){
					var txt = name.slice(0,upper.indexOf(keyword.toLocaleUpperCase()))+'<span class="alert alert-error">'+keyword+'</span>'+name.slice(upper.indexOf(keyword.toLocaleUpperCase())+keyword.length,length);
					if(i%2==0)
					$('table tbody td:eq('+i+') a').html(txt);
					else 
					elem.html(txt);
				}
			}
		}
		
		
		if(parseInt(index)==1){
			var len = $('table tbody td').length;
			for(var i=0;i<len;i++){
				if(i%2==0){
					var keyword = $('#keyword-find').text();
					var title_elem = $('table tbody td:eq('+i+')');
					var title_name = title_elem.text();
					var upper_name = title_name.toLocaleUpperCase(); 
					var title_length = title_name.length;
					var txt = title_name.slice(0,upper_name.indexOf(keyword.toLocaleUpperCase()))+'<span class="alert alert-error">'+keyword+'</span>'+title_name.slice(upper_name.indexOf(keyword.toLocaleUpperCase())+keyword.length,title_length);
					$('table tbody td:eq('+i+') a').html(txt);
					//title_elem.html(txt);
				}
			}
		}
		if(parseInt(index)==2){
			var len = $('table tbody td').length;
			for(var i=0;i<len;i++){
				if(i%2==1){
					var keyword = $('#keyword-find').text();
					var author_elem = $('table tbody td:eq('+i+')');
					var author_name = author_elem.text();
					var upper_author = author_name.toLocaleUpperCase(); 
					var author_length = author_name.length;
					var txt = author_name.slice(0,upper_author.indexOf(keyword.toLocaleUpperCase()))+'<span class="alert alert-error">'+keyword+'</span>'+author_name.slice(upper_author.indexOf(keyword.toLocaleUpperCase())+keyword.length,author_length);
					author_elem.html(txt);
				}
			}
		}
		$(".tooltip-target").ezpz_tooltip();
		
		
				
	})
</script>

CrazyLib/app/views/books/_search_results.html.erb
 <% if @books%>
 <div class="text-info">
 	<%=t :found%> <%=@books.length%> <%=t :result, :count => @books.length%>.
 </div>
  <table class="table table-hover">
              <thead>
                <tr>
                  <th><%=t :title%></th>
                  <th><%=t :author%></th>
                </tr>
              </thead>
              <tbody>
              <% @books.each do |book| %>          
                <tr>  
                  <td class="tooltip-target" id="example-target-<%=book.id%>" ><%= link_to book.title, 
                      :action => 'view',:topic=>book.topic ,:id => book.id  %>
                      <img class="tooltip-content" id='example-content-<%=book.id%>' style="display:none;position:absolute;"src="../assets/<%=book.image_url%>" width="150" height="150"></img>
                      </td>
                  <td><%=book.author%>
                  </td>
                </tr>
              <% end %>              
              </tbody>
            </table>
  <% else %>
<% end%>

CrazyLib/app/views/books/_topbar.html.erb
<!--top bar-->
<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
			<div class="nav-collapse collapse navbar-responsive-collapse">
				<ul class="nav">
					<li>
						<a href="#"><%=t :nominate%></a>
					</li>
					<li>
						<a href="/books/newbook"><%=t :new_book%></a>
					</li>
					<li>
						<a href="/books/popular"><%=t :most_popular%></a>
					</li>
					

				</ul>
				<!--<form class="navbar-search pull-right " action="">
					<!--
					%= render :partial => 'books/search' %
					/-->
					<!--<input type="text" class="search-query span12" placeholder="<%=t :search%>">
				</form>-->
			</div><!-- /.nav-collapse -->
		</div>
	</div><!-- /navbar-inner -->
</div>
<!--end-->

CrazyLib/app/views/books/_viewtype.html.erb
	<!--one type of book-->
	<div class="books-content">
	<div class="row-fluid">
		<%@sciences = Books.find(:all,:conditions=>{:topic=>params[:type]})%>
		  <h3 class="pull-left ">
			<div class="btn-group"><a class="btn" href="viewbytype?type=1">Sách khoa học</a></div>
		  </h3>
	</div>
	<div class="row-fluid" id="science-content">
				<%i = 0;%>
				<% @sciences.each do |science| %>
				<%if(i%4==0)%>
				<ul class="thumbnails">
				<%end%>
				<li class="span3" >
				<div class="thumbnail">
				  <a href="viewbyid?id=<%= science.bookId%>&type=1" ><img src="../assets/<%= science.url%>" alt=""></a>
				  <div class="caption">
					<!--<h3 style="font-size:20px;"> <%= science.title%></h3>-->
					<p>
						<%=  truncate(science.content,:length=>80)%>
					</p>
				  </div>
				</div>
				</li>
				<%if(i%4==3)%>
				</ul>
				<%end%>
				<%i=i+1%>
				
				<% end %>
	</div>
	</div>
	<!--end-->
	

CrazyLib/app/views/books/edit.html.erb
<%if user_signed_in?%>
  <%if current_user.group ==3%>
<h1>Editing book</h1>

<%= render 'form' %>

<%end%>
<%end%>

CrazyLib/app/views/books/list_all_book.erb
<%Books.count%>

CrazyLib/app/views/books/new.html.erb
<%if user_signed_in?%>
<%if current_user.group ==3%>
<%= render 'form' %>
<%end%>
<%end%>

CrazyLib/app/views/books/popular.html.erb
<div class="container-fluid">
	<div class="span10">
		<%= render 'topbar'%>
		<div class="books-content">
		<% i = 0;%>
	<% @books.each do |b| %>
		<%if(i%4==0)%>
		<ul class="thumbnails">
		<%end%>
			<li class="span3" >
				<div class="thumbnail">
					<a href="view?topic=<%=b.topic%>&id=<%= b.id%>&locale=<%=I18n.locale%>" ><img src="../assets/<%= b.image_url%>" alt=""></a>
					<div class="caption">
						
						
						<p class="text-success"><i class="icon-eye-open"></i>   Book views : <%=b.seen_by%> views</p>
						<p class="text-success"><i class="icon-th-large"></i>   Public : <%=b.created_at.strftime("%d-%m-%Y")%> </p>
						
						<h6 class="text-error">
							<%=truncate(b.title,:length=>50)%>
						</h6>
						<p>
							<%= truncate(b.brief_content,:length=>80)%>
						</p>
					</div>
				</div>
			</li>
			<%if(i%4==3)%>
		</ul>
		<%end%>		
	<% i=i+1%>
	<% end %>
	</div>
	</div>
	<div class="span2">
		<%= render 'rightbar'%>
	</div>
</div>

CrazyLib/app/views/books/search.html.erb
<div class="container-fluid">
	<div class="span10">
		<%= render 'topbar'%>
		<div class="books-content">
			<%= render 'search'%>
		</div>
	</div>
	<div class="span2">
		<%= render 'rightbar'%>
	</div>
</div>

CrazyLib/app/views/books/show_all.html.erb
<p id="notice">
	<%= notice %>
</p>
<table class="table table-bordered table-hover">
	<thead class="label-info">
		<th><%=t :book_id%></th>
		<th><%=t :book_title%></th>
		<th><%=t :book_author%></th>
		<th><%=t :book_publisher%></th>
		<th><%=t :book_content%></th>
		<th><%=t :book_page%></th>
		<th><%=t :book_topic%></th>
		<th><%=t :book_quantity%></th>
		<th><%=t :book_current_quantity%></th>
		<th></th>
	</thead>

	<% @books.each do |book| %>
	<tr>
		<td><%= book.id %></td>
		<td><%= book.title %></td>
		<td><%= book.author %></td>
		<td><%= book.publisher %></td>
		<td><%= book.brief_content %></td>
		<td><%= book.total_page %></td>
		<td><%= book.bookTopic(Integer(book.topic)) %></td>
		<td><%= book.quantity %></td>
		<td><%= book.current_quantity %></td>
		<td><a href="/books/<%= book.id%>/edit">
		<div class="text-warning">
			<%=t :edit%>
		</div></a></td>
	</tr>
	<% end %>
</table>

CrazyLib/app/views/books/view.html.erb
<div class="container-fluid">
	<div class="span10">
		<%= render 'topbar'%>
		<%= render 'onebook'%>
	</div>
	<div class="span2">
		<%= render 'rightbar'%>
	</div>
</div>

CrazyLib/app/views/books/viewbytype.html.erb
<div class="container-fluid">
	<div class="span10">
		<%= render 'topbar'%>
		<%= render 'viewtype'%>
	</div>
	<div class="span2">
		<%= render 'rightbar'%>
	</div>
</div>